version: "3.9"

services:
  # ----------------------
  # PostgreSQL
  # ----------------------
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: packetuser
      POSTGRES_PASSWORD: packetpass
      POSTGRES_DB: packetdb
    ports:
      - "5432:5432"
    networks:
      - packet-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U packetuser -d packetdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ----------------------
  # pgAdmin
  # ----------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - packet-net
    depends_on:
      db:
        condition: service_healthy

  # ----------------------
  # Microservices
  # ----------------------
  persistor-service:
    image: ${DOCKERHUB_USER}/persistor-service:latest
    container_name: persistor-service
    environment:
      SERVICE_PORT: 5002
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5002:5002"
    networks:
      - packet-net
    depends_on:
      db:
        condition: service_healthy

  parser-service:
    image: ${DOCKERHUB_USER}/parser-service:latest
    container_name: parser-service
    environment:
      SERVICE_PORT: 5001
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5001:5001"
    networks:
      - packet-net
    depends_on:
      db:
        condition: service_healthy
      persistor-service:
        condition: service_started

  analyzer-service:
    image: ${DOCKERHUB_USER}/analyzer-service:latest
    container_name: analyzer-service
    environment:
      SERVICE_PORT: 5003
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5003:5003"
    networks:
      - packet-net
    depends_on:
      parser-service:
        condition: service_started

  ui-service:
    image: ${DOCKERHUB_USER}/ui-service:latest
    container_name: ui-service
    environment:
      SERVICE_PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - packet-net
    depends_on:
      analyzer-service:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

  capture-service:
    image: ${DOCKERHUB_USER}/capture-service:latest
    container_name: capture-service
    environment:
      SERVICE_PORT: 5004
      IFACE: ens5
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    depends_on:
      parser-service:
        condition: service_started  
        
  splunk-uf:
  image: splunk/universalforwarder:latest
  container_name: splunk-uf
  hostname: splunk-uf
  environment:
    SPLUNK_GENERAL_TERMS: "--accept-sgt-current-at-splunk-com"
    SPLUNK_START_ARGS: "--accept-license"
    SPLUNK_PASSWORD: simla@123
    SPLUNK_FORWARD_SERVER: "3.110.195.161:9997" # <-- Splunk Master 
    SPLUNK_ADD: "monitor /var/lib/docker/containers"
  volumes:
    - ./uf-config:/opt/splunkforwarder/etc/system/local
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
  networks:
    - packet-net


networks:
  packet-net:
    driver: bridge
