services:

  # ----------------------
  # PostgreSQL
  # ----------------------
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_USER: packetuser
      POSTGRES_PASSWORD: packetpass
      POSTGRES_DB: packetdb
    ports:
      - "5432:5432"
    networks:
      - packet-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U packetuser -d packetdb"]
      interval: 10s
      timeout: 5s
      retries: 10

  # ----------------------
  # pgAdmin
  # ----------------------
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    networks:
      - packet-net
    depends_on:
      db:
        condition: service_healthy

  # ----------------------
  # Microservices
  # ----------------------
  persistor-service:
    image: ${DOCKERHUB_USER}/persistor-service:latest
    container_name: persistor-service
    environment:
      SERVICE_PORT: 5002
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5002:5002"
    networks:
      - packet-net
    logging:
      driver: splunk
      options:
        splunk-url: "http://localhost:8088"
        splunk-token: "798093f9-13b1-4cdf-952a-01861b4dad85"
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        tag: "persistor-service"
    depends_on:
      splunk:
        condition: service_healthy
      db:
        condition: service_healthy

  parser-service:
    image: ${DOCKERHUB_USER}/parser-service:latest
    container_name: parser-service
    environment:
      SERVICE_PORT: 5001
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5001:5001"
    networks:
      - packet-net
    logging:
      driver: splunk
      options:
        splunk-url: "http://localhost:8088"
        splunk-token: "798093f9-13b1-4cdf-952a-01861b4dad85"
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        tag: "parser-service"
    depends_on:
      splunk:
        condition: service_healthy
      persistor-service:
        condition: service_started

  analyzer-service:
    image: ${DOCKERHUB_USER}/analyzer-service:latest
    container_name: analyzer-service
    environment:
      SERVICE_PORT: 5003
      DATABASE_URL: "postgresql://packetuser:packetpass@db:5432/packetdb"
    ports:
      - "5003:5003"
    networks:
      - packet-net
    logging:
      driver: splunk
      options:
        splunk-url: "http://localhost:8088"
        splunk-token: "798093f9-13b1-4cdf-952a-01861b4dad85"
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        tag: "analyzer-service"
    depends_on:
      splunk:
        condition: service_healthy
      parser-service:
        condition: service_started

  ui-service:
    image: ${DOCKERHUB_USER}/ui-service:latest
    container_name: ui-service
    environment:
      SERVICE_PORT: 5000
    ports:
      - "5000:5000"
    networks:
      - packet-net
    logging:
      driver: splunk
      options:
        splunk-url: "http://localhost:8088"
        splunk-token: "798093f9-13b1-4cdf-952a-01861b4dad85"
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        tag: "ui-service"
    depends_on:
      splunk:
        condition: service_healthy
      analyzer-service:
        condition: service_started
    extra_hosts:
      - "host.docker.internal:host-gateway"

  capture-service:
    image: ${DOCKERHUB_USER}/capture-service:latest
    container_name: capture-service
    environment:
      SERVICE_PORT: 5004
      IFACE: ens5
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: always
    logging:
      driver: splunk
      options:
        splunk-url: "http://localhost:8088"
        splunk-token: "798093f9-13b1-4cdf-952a-01861b4dad85"
        splunk-insecureskipverify: "true"
        splunk-format: "json"
        tag: "capture-service"
    depends_on:
      splunk:
        condition: service_healthy
      parser-service:
        condition: service_started

networks:
  packet-net:
    driver: bridge
